AWSTemplateFormatVersion: '2010-09-09'
Description: Create Route53 Resolver and related resources.

## ::PARAMETERS::
## Template parameters to be configured by user
Parameters:
  stackVpcId:
    Type: AWS::EC2::VPC::Id
    Description: Specify the VPC id.

  stackVpcCidr:
    Type: String
    Description: Specify the CIDR assigned to the VPC.
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: "Must be a valid IP range of the form x.x.x.x/x"

  stackPrivateSubnet1:
    Type: AWS::EC2::Subnet::Id
    Description: Specify the private subnet id.

  stackPrivateSubnet1IpAddress:
    Type: String
    Description: Specify the private subnet ip address.

  stackPrivateSubnet2:
    Type: AWS::EC2::Subnet::Id
    Description: Specify the private subnet id.

  stackPrivateSubnet2IpAddress:
    Type: String
    Description: Specify the private subnet ip address.

  stackENIPrivateIpAddress1:
    Type: String
    Description: Specify the ENI private ip address.

  stackENIPrivateIpAddress2:
    Type: String
    Description: Specify the ENI private ip address.

  stackEC2InstanceType:
    Type: String
    Description: Specify the EC2 instance type used for the resolver endpoint.

  stackDomainName:
    Type: String
    Description: Specify domain name.
    Default: ""

## ::METADATA::
## CloudFormation parameter UI definitions
Metadata:
  "AWS::CloudFormation::Interface":
    ParameterGroups:
      - Label:
          default: VPC & Subnet Configuration
        Parameters:
          - stackVpcId
          - stackVpcCidr
          - stackPrivateSubnet1
          - stackPrivateSubnet1IpAddress
          - stackPrivateSubnet2
          - stackPrivateSubnet2IpAddress
      - Label:
          default: NetworkInterface Configuration
        Parameters:
          - stackENIPrivateIpAddress1
          - stackENIPrivateIpAddress2
      - Label:
          default: ResolverEndpoint Configuration
        Parameters:
          - stackEC2InstanceType    
      - Label:
          default: DomainName Configuration
        Parameters:
          - stackDomainName

    ParameterLabels:
      stackVpcId:
        default: VPC ID
      stackVpcCidr:
        default: VPC Cidr
      stackPrivateSubnet1:
        default: Private Subnet
      stackPrivateSubnet1IpAddress:
        default: Private Subnet IP Address
      stackPrivateSubnet2: 
        default: Private Subnet
      stackPrivateSubnet2IpAddress:
        default: Private Subnet IP Address
      stackENIPrivateIpAddress1:
        default: ENI Private IP Address
      stackENIPrivateIpAddress2:
        default: ENI Private IP Address
      stackDomainName:
        default: Domain Name

## ::CONDITIONS::
## Determines if we're generating regional or global resources

## ::RESOURCES::
## Resources used in this solution
Resources:
  InboundResolverSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref stackVpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 53
          ToPort: 53
          CidrIp: !Ref stackVpcCidr
        - IpProtocol: udp
          FromPort: 53
          ToPort: 53
          CidrIp: !Ref stackVpcCidr
      Tags:
        - Value: name
          Key: ecms-resolever-securitygroup
          
  InboundResolverEndpoint:
    Type: AWS::Route53Resolver::ResolverEndpoint
    Properties:
      Direction: INBOUND
      PreferredInstanceType: !Ref stackEC2InstanceType
      ResolverEndpointType: IPV4
      IpAddresses:
        - SubnetId: !Ref stackPrivateSubnet1
          Ip: !Ref stackPrivateSubnet1IpAddress
        - SubnetId: !Ref stackPrivateSubnet1
          Ip: !Ref stackPrivateSubnet2IpAddress
      SecurityGroupIds:
        - !Ref InboundResolverSecurityGroup
      Name: ecms-resolver-endpoint
      Tags:
        - Value: Name
          Key: ecms-resolver-endpoint

  ResolverRule:
    Type: AWS::Route53Resolver::ResolverRule
    Properties:
      DomainName: !Ref stackDomainName
      RuleType: FORWARD
      ResolverEndpointId: !Ref InboundResolverEndpoint
      TargetIps:
        - Ip: !Ref stackENIPrivateIpAddress1
          Port: 53
        - Ip: !Ref stackENIPrivateIpAddress2
          Port: 53
      Name: ecms-resolver-rule
      Tags:
        - Key: Name
          Value: ecms-resolver-rule

  ResolverRuleAssociation:
    Type: AWS::Route53Resolver::ResolverRuleAssociation
    Properties:
      ResolverRuleId: !Ref ResolverRule
      VPCId: !Ref stackVpcId
      Name: ecms-resolver-association

Outputs:
  SecurityGroupId:
    Description: Security Group Id
    Value: !Ref InboundResolverSecurityGroup

  ResolverEndpointId:
    Description: Resolver Endpoint Id
    Value: !Ref InboundResolverEndpoint

